//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_Track
    {
        public int idstation_start { get; set; }
        public int idstation_stop { get; set; }
        public int idtrack { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual Track Track { get; set; }
    }
}
