//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.Station_Track = new HashSet<Station_Track>();
        }
    
        public int id { get; set; }
        public int weight { get; set; }
        public string comment { get; set; }
    
        public virtual ICollection<Station_Track> Station_Track { get; set; }
    }
}
